DELETE http://localhost:3001/api/persons/whatever

###
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "harry",
    "number": "123-456"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{

}

###
POST https://phonebook-wg9t.onrender.com/api/persons
content-type: application/json

{

}

###
POST https://phonebook-wg9t.onrender.com/api/persons
content-type: application/json

{
    "name": "potter",
    "number": "123-456"
}