DELETE http://localhost:3001/api/persons/whatever

###
PUT http://localhost:3001/api/persons/673308d096e47374568c6127
content-type: application/json

{
    "name": "Anna",
    "number": "123"
}

###
POST http://localhost:3001/api/persons
content-type: application/json

{

}

###
POST https://phonebook-wg9t.onrender.com/api/persons
content-type: application/json

{

}

###
POST https://phonebook-wg9t.onrender.com/api/persons
content-type: application/json

{
    "name": "potter",
    "number": "123-456"
}